Add linux-arm64 to releases
carvel-dev/imgpkg pull request #356
Opened 2022-03-15 15:27 UTC by benmoss

Fixes https://github.com/vmware-tanzu/carvel-imgpkg/issues/352

2022-03-16 16:12 UTC, joaopapereira requested changes
There is another place that needs some change.

the step `get-checksums-from-draft-release` when we are retrieving the checksums, needs to change to include the checksum of the arm version.
Also the `hack/build-binaries.sh` script also need to manually create the arm version so that we can validate the output of the Github action step.

I think that should be it

2022-03-16 19:23 UTC, benmoss commented
@joaopapereira updated!

2022-03-16 21:08 UTC, joaopapereira commented on hack/build-binaries.sh
>  shasum -a 256 ./imgpkg-darwin-amd64 ./imgpkg-darwin-arm64 ./imgpkg-linux-amd64 ./imgpkg-windows-amd64.exe
It is missing the arm shasum in this line

2022-03-16 21:29 UTC, benmoss commented on hack/build-binaries.sh
>  shasum -a 256 ./imgpkg-darwin-amd64 ./imgpkg-darwin-arm64 ./imgpkg-linux-amd64 ./imgpkg-windows-amd64.exe
Good catch

2022-03-17 14:54 UTC, joaopapereira approved these changes
LGTM, we should in the future try to get this more automated in some way without having to change so many places

2022-03-17 14:55 UTC, merged