Bumping goreleaser to latest version
carvel-dev/imgpkg pull request #529
Opened 2023-05-30 16:40 UTC by sethiyash

2023-05-30 17:45 UTC, joaopapereira requested changes
I think the goreleaser version is incorrect

2023-05-30 17:45 UTC, joaopapereira commented on .github/workflows/release.yml
> +          version: 0.16.2
```suggestion
          version: 1.16.2
```

2023-05-31 05:33 UTC, sethiyash commented on .github/workflows/release.yml
> +          version: 0.16.2
Good Catch! Thanks, Joao.

2023-05-31 08:01 UTC, joaopapereira approved these changes
LGTM

2023-05-31 16:21 UTC, merged