Adding golint and goheader linters via golangci-lint
carvel-dev/imgpkg pull request #58
Opened 2021-01-15 15:13 UTC by danielhelfand

This pull requests adds a linting tool ([golangci-lint](https://github.com/golangci/golangci-lint)) to `imgpkg`. `golangci-lint` allows users to add go linters to a project via a config file (`.golangci.yml`).

For this initial introduction of linting to the project, [`golint`](https://github.com/golang/lint#purpose) and [`go-header`](https://github.com/denis-tingaikin/go-header#go-header) are being added. `golint` helps to address styling issues associated with go projects. `go-header` checks if copyright headers are present for files in a project.

The introduction of `go-header` will help prevent checking in files with no license headers. All `golint` issues were fixed as part of introducing this change as well.

2021-01-15 16:30 UTC, joaopapereira requested changes
This looks good.
I would like the linter to run as part of our hack/build.sh or at least as part of our workflows. Can you do that change?

2021-01-15 16:41 UTC, danielhelfand commented
@joaopapereira From a CI standpoint, I think it would make sense to not run this as part of the test-gh action. It should be run in parallel and results should be reported separately than the action that builds/tests.

If we want to introduce it to the build script, it should then have some condition to not run in that test-gh action. We have a separate story for adding this to CI where we could maybe further explore what makes sense.

2021-01-15 17:02 UTC, danielhelfand commented
A potential compromise here would be to have a separate build-and-lint.sh script that calls build and also runs the linting process.

2021-01-15 20:57 UTC, joaopapereira commented
In my opinion, the user value from having the linter is to have it run automatically, so I would prefer to have the integration of the linter in our CI in this same PR.

2021-01-15 22:16 UTC, danielhelfand commented
Yeah, I think it's fair. Let's put this on hold then as we are waiting on a fix for go-header to be available in the next golangci-lint release. That is the hold up on introducing in CI.

2021-01-19 15:55 UTC, danielhelfand commented
The linter has been added to CI.

2021-01-19 16:12 UTC, joaopapereira approved these changes
LGTM

2021-01-19 17:16 UTC, merged